menus/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "menus"

urlpatterns = [
    path('', views.menus_page, name='menus'),
    path('create/', views.create_menu, name="create"),
    path('<slug:slug>/', views.menu_page, name="menu"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('contact/', views.contact_page, name='contact'),
    path('menus/', include('menus.urls')),
    path("accounts/", include("allauth.urls")),
    path('reservations/', include('reservations.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservations/urls.py
from django.urls import path

from . import views

app_name = "reservations"

urlpatterns = [
    path('', views.reservation_page, name="reservations"),
    path('liste/', views.liste_reservation, name="liste"),
    path('edit/<list_id>', views.edit, name="edit"),
    path('delete/<int:list_id>', views.delete_reservation, name="delete"),
]

mysite/forms.py
"""
This module defines the ContactForm used on the contact page.
It collects the user's name, email, and message.
"""

from django import forms


class ContactForm(forms.Form):
    """
    A simple contact form.

    This form gathers a user's name, email,
    and message to be sent to the site administrators.
    """
    name = forms.CharField(max_length=250)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

    class Meta:
        fields = ['name', 'email', 'message']

templates/contact.html
{% extends 'template_base.html' %}
{% load widget_tweaks %}

{% block content %}
<!-- Contact Page -->
<div class="contact-page mb-5">
    <h1>Contact Us</h1>
    <!-- Contact form that posts to the 'contact' URL -->
    <form action="{% url 'contact' %}" method="POST">
        {% csrf_token %}
        <!-- Form group for name input -->
        <div class="form-group">
            <label for="id_name">Name:</label>
            {{ form.name }}
            <span class="error-message" id="nameError"></span>
        </div>
        <!-- Form group for email input -->
        <div class="form-group">
            <label for="id_email">Email:</label>
            {{ form.email }}
            <span class="error-message" id="emailError"></span>
        </div>
        <!-- Form group for message textarea -->
        <div class="form-group">
            <label for="id_message">Message:</label>
            {{ form.message|add_class:"text-area" }}
            <span class="error-message" id="messageError"></span>
        </div>
        <!-- Submit button for the form -->
        <button type="submit" class="btn btn-primary btn-lg w-100">Submit</button>
    </form>
</div>
{% endblock %}

templates/home.html
{% extends 'template_base.html' %}

{% block content %}
<!-- Home Page Content -->
<div id="container" class="home-page h-100 text-center">
    <h1 class="display-3 text-white text-center">
        Let's <span class="text-primary">enjoy</span>.
    </h1>
    <p class="lead fw-bolder text-white text-cetner my-4">
        We bring over 30 years of industry experience and passion to Moroc. With
        dishes that are carefully designed to bring you a truly satisfying
        Moroccan food experience that you are sure to remember.
    </p>
    <!-- Button linking to the reservation page -->
    <p class="lead text-center mb-0 mt-sm-5">
        <a
            href="{% url 'reservations:reservations' %}"
            class="fs-5 fw-bold btn btn-light bg-primary text-white"
            style="padding: 15px 30px; border-radius: 5px"
        >
            MAKE A RESERVATION
        </a>
    </p>
</div>
{% endblock %}

templates/index.html
{% extends 'template_base.html' %} {% load static %} {% block content %}
<style>
    html,
    body {
        background: url('/media/presentation.jpg') no-repeat center center fixed;
        background-size: cover;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
    }

    
</style>

<main class="px-3 text-start text-white mt-5 h-100">
    <h1 class="display-1">Let's <span class="text-warning">enjoy</span>.</h1>
    <p class="lead fw-bolder">
        We love sharing good food with great people. We bring over 30 years
        industry experience and passion to Moroc. With a dishes that are
        carefully designed to bring you a truly satisfying Moroccan food
        experience that you are sure to remember.
    </p>
    <p class="lead">
        <a href="{% url 'reservations:reservations' %}" class="text-white">
            MAKE A RESERVATION
        </a>
    </p>
</main>

{% endblock %}

templates/template_base.html
{# template_base.html - Base template used for common layout (header, footer, etc.) #}
{% url 'account_login' as login_url %} 
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}

<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <!-- Favicon -->
        <link rel="icon" type="image/x-icon" href="{% static 'images/logo.png' %}" />
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
        <script src="https://kit.fontawesome.com/d89ffbeb14.js" crossorigin="anonymous"></script>
        <title>{% block title %}Moroc{% endblock %}</title>
    </head>
    <body>
        <!-- Header Section -->
        <header>
            <nav class="navbar navbar-dark navbar-expand-md {% if request.resolver_match.url_name == 'home' %}navbar-home{% else %}navbar-other{% endif %}">
                <div class="container-fluid">
                    <a class="navbar-brand text-white fs-2 moroc-logo" href="{% url 'home' %}">
                        <img src="{% static 'images/logo.png' %}" alt="logo" />Moroc
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
                        <ul class="navbar-nav ms-auto">
                            {# Navigation links #}
                            <li class="nav-item">
                                <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}" aria-current="page" href="{% url 'home' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if request.resolver_match.url_name == 'contact' %}active{% endif %}" href="{% url 'contact' %}">Contact</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if request.resolver_match.url_name == 'menus' %}active{% endif %}" href="{% url 'menus:menus' %}">Menus</a>
                            </li>
                            {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Reservations</a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" href="{% url 'reservations:liste' %}">Edit/List</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="{% url 'reservations:reservations' %}">Reservations</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ logout_url }}">Logout</a>
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ login_url }}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ signup_url }}">Sign Up</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <!-- Main Content Section -->
        <main>
            {% if messages %}
            <div class="container mt-3 text-white">
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show text-center position-relative bg-primary text-white" role="alert">
                    <button type="button" class="btn-close btn-danger position-absolute top-0 end-0 me-1 mt-0" data-bs-dismiss="alert" aria-label="Close"></button>
                    {{ message }}
                </div>
                {% endfor %}
            </div>
            {% endif %}
            {% block content %}{% endblock %}
        </main>

        <!-- Footer Section -->
        <footer>
            <div class="icon text-center text-white">
                <a href="https://www.facebook.com" target="_blank" aria-label="Visit our Facebook page">
                    <i class="fa-brands fa-facebook" aria-hidden="true"></i>
                </a>
                <a href="https://www.instagram.com/" target="_blank" aria-label="Visit our Instagram profile">
                    <i class="fa-brands fa-instagram" aria-hidden="true"></i>
                </a>
                <a href="https://x.com/?lang=en" target="_blank" aria-label="Visit our Twitter page">
                    <i class="fa-brands fa-x-twitter" aria-hidden="true"></i>
                </a>
            </div>
        </footer>

        <!-- Bootstrap JS Bundle -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>